name = "quotient-ring-modulo-power-of-maximal-ideal"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["QuotientRingModuloPowerOfMaximalIdeal"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "QuotientRingModuloPowerOfMaximalIdeal"
